-- DROP TABLE IF EXISTS endpoint_hits CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hits
(
    hit_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name         VARCHAR(20) NOT NULL,
    hit_uri          VARCHAR(20) NOT NULL,
    user_ip          VARCHAR(20) NOT NULL,
    time_stamp       TIMESTAMP NOT NULL
);